---
APPLY_FIXES: none
VALIDATE_ALL_CODEBASE: true

ENABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  - YAML_YAMLLINT
  - JSON_JSONLINT
  - BASH_SHELLCHECK

MARKDOWN_MARKDOWNLINT_FILTER_REGEX_INCLUDE: "(README|CHEATSHEET|AGENTS|CLAUDE)\\.md"
YAML_YAMLLINT_FILTER_REGEX_INCLUDE: "(\\.github/)"
JSON_JSONLINT_FILTER_REGEX_INCLUDE: "(package\\.json)"

MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: true
